# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-25 23:07
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('driver', '0003_furnace'),
    ]

    operations = [
        migrations.AddField(
            model_name='furnace',
            name='pub_date',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name=b'date published'),
            preserve_default=False,
        ),
    ]
