# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-26 22:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('driver', '0004_furnace_pub_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='Furnacework',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('temp', models.CharField(max_length=200)),
                ('pub_date', models.DateTimeField(verbose_name=b'date published')),
            ],
        ),
    ]
