# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-09 18:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('driver', '0009_settings'),
    ]

    operations = [
        migrations.CreateModel(
            name='Powersettings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first', models.CharField(max_length=200)),
                ('second', models.CharField(max_length=200)),
                ('third', models.CharField(max_length=200)),
                ('fourth', models.CharField(max_length=200)),
                ('fifth', models.CharField(max_length=200)),
                ('pub_date', models.DateTimeField(verbose_name=b'date published')),
            ],
        ),
    ]
