# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-09 22:21
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('driver', '0010_powersettings'),
    ]

    operations = [
        migrations.AddField(
            model_name='setusertemp',
            name='usertempnight',
            field=models.CharField(default=django.utils.timezone.now, max_length=200),
            preserve_default=False,
        ),
    ]
