# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-09 22:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('driver', '0011_setusertemp_usertempnight'),
    ]

    operations = [
        migrations.CreateModel(
            name='Dayandnight',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timeofday', models.CharField(max_length=200)),
                ('pub_date', models.DateTimeField(verbose_name=b'date published')),
            ],
        ),
    ]
