# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-09 22:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('driver', '0012_dayandnight'),
    ]

    operations = [
        migrations.AddField(
            model_name='dayandnight',
            name='count',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
    ]
